   name: Node app CI

   on: [push]

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: MongoDB in GitHub Actions
           uses: supercharge/mongodb-github-action@1.3.0
         - name: Use Node.js
           uses: actions/setup-node@v1
         - run: npm install
         - run: npm test
